### ISSUE TITLE
New way to enforce a space between selector and the curly brace

### ISSUE THREAD

**Issue by edizcelik** [Hipo/stylelint-config-hipo-base#5]
Currently, stylelint does not raise an error for the following line:

```
.investor-detail-summary-accounts-panel-account-box-alert-icon{
```

Let's investigate if there is a way to enforce a space before the opening curly brace

**Comment by mucahit** [comment]
Let's add [`block-opening-brace-space-before`](https://stylelint.io/user-guide/rules/block-opening-brace-space-before#block-opening-brace-space-before)

**Comment by burakguneli** [comment]
This issue solved with the new release.
